;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2009-3-6 14:53:06

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1004=index.html	; 领先网络科技CMS使用文档
IDH_1000=IndexShow.html	; 首页标签-通用标签
IDH_1005=IndexLabel.html	; 首页标签-通用标签-系统配置
IDH_1001=IndexShow1.html	; 首页标签-首页调用标签
IDH_1002=IndexShow2.html	; 首页标签-首页调用标签
IDH_1003=indexShow3.html	; 首页调用-首页新闻标签样式
