;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2009-3-6 14:53:06

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1004	1004	; 领先网络科技CMS使用文档 index.html
#define IDH_1000	1000	; 首页标签-通用标签 IndexShow.html
#define IDH_1005	1005	; 首页标签-通用标签-系统配置 IndexLabel.html
#define IDH_1001	1001	; 首页标签-首页调用标签 IndexShow1.html
#define IDH_1002	1002	; 首页标签-首页调用标签 IndexShow2.html
#define IDH_1003	1003	; 首页调用-首页新闻标签样式 indexShow3.html
